<?php

if (!defined('ABSPATH')) exit;

$gdwft_fonts_list = array(
    'abel' => array('family' => 'Abel', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'abel'), 
    'abril-fatface' => array('family' => 'Abril Fatface', 'variants' => array('n4', 'i4'), 'subsets' => array(''), 'slug' => 'abril-fatface'), 
    'aclonica' => array('family' => 'Aclonica', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'aclonica'), 
    'acme' => array('family' => 'Acme', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'acme'), 
    'actor' => array('family' => 'Actor', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'actor'), 
    'adamina' => array('family' => 'Adamina', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'adamina'), 
    'advent-pro' => array('family' => 'Advent Pro', 'variants' => array('n1', 'n2', 'n3', 'n4', 'n5', 'n6', 'n7'), 'subsets' => array(''), 'slug' => 'advent-pro'), 
    'aguafina-script' => array('family' => 'Aguafina Script', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'aguafina-script'), 
    'aladin' => array('family' => 'Aladin', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'aladin'), 
    'alegreya' => array('family' => 'Alegreya', 'variants' => array('n4', 'i4', 'n7', 'i7', 'n9', 'i9'), 'subsets' => array(''), 'slug' => 'alegreya'), 
    'alegreya-sc' => array('family' => 'Alegreya SC', 'variants' => array('n4', 'i4', 'n7', 'i7', 'n9', 'i9'), 'subsets' => array(''), 'slug' => 'alegreya-sc'), 
    'alex-brush' => array('family' => 'Alex Brush', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'alex-brush'), 
    'alexa-std' => array('family' => 'Alexa Std', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'alexa-std'), 
    'alfa-slab-one' => array('family' => 'Alfa Slab One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'alfa-slab-one'), 
    'alice' => array('family' => 'Alice', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'alice'), 
    'alike' => array('family' => 'Alike', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'alike'), 
    'alike-angular' => array('family' => 'Alike Angular', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'alike-angular'), 
    'allan' => array('family' => 'Allan', 'variants' => array('n7'), 'subsets' => array(''), 'slug' => 'allan'), 
    'allerta' => array('family' => 'Allerta', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'allerta'), 
    'allura' => array('family' => 'Allura', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'allura'), 
    'almendra' => array('family' => 'Almendra', 'variants' => array('n4', 'i4', 'n7'), 'subsets' => array(''), 'slug' => 'almendra'), 
    'almendra-sc' => array('family' => 'Almendra SC', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'almendra-sc'), 
    'amaranth' => array('family' => 'Amaranth', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'amaranth'), 
    'amatic-sc' => array('family' => 'Amatic SC', 'variants' => array('n4', 'n7'), 'subsets' => array(''), 'slug' => 'amatic-sc'), 
    'amethysta' => array('family' => 'Amethysta', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'amethysta'), 
    'andada' => array('family' => 'Andada', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'andada'), 
    'andika' => array('family' => 'Andika', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'andika'), 
    'annie-use-your-telescope' => array('family' => 'Annie Use Your Telescope', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'annie-use-your-telescope'), 
    'anonymous-pro' => array('family' => 'Anonymous Pro', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'anonymous-pro'), 
    'antic' => array('family' => 'Antic', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'antic'), 
    'antic-didone' => array('family' => 'Antic Didone', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'antic-didone'), 
    'antic-slab' => array('family' => 'Antic Slab', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'antic-slab'), 
    'arapey' => array('family' => 'Arapey', 'variants' => array('n4', 'i4'), 'subsets' => array(''), 'slug' => 'arapey'), 
    'arbutus' => array('family' => 'Arbutus', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'arbutus'), 
    'architects-daughter' => array('family' => 'Architects Daughter', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'architects-daughter'), 
    'arimo' => array('family' => 'Arimo', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'arimo'), 
    'arizonia' => array('family' => 'Arizonia', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'arizonia'), 
    'artifika' => array('family' => 'Artifika', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'artifika'), 
    'arvo' => array('family' => 'Arvo', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'arvo'), 
    'asap' => array('family' => 'Asap', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'asap'), 
    'asset' => array('family' => 'Asset', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'asset'), 
    'astloch' => array('family' => 'Astloch', 'variants' => array('n4', 'n7'), 'subsets' => array(''), 'slug' => 'astloch'), 
    'asul' => array('family' => 'Asul', 'variants' => array('n4', 'n7'), 'subsets' => array(''), 'slug' => 'asul'), 
    'atomic-age' => array('family' => 'Atomic Age', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'atomic-age'), 
    'aubrey' => array('family' => 'Aubrey', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'aubrey'), 
    'average' => array('family' => 'Average', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'average'), 
    'averia-gruesa-libre' => array('family' => 'Averia Gruesa Libre', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'averia-gruesa-libre'), 
    'averia-libre' => array('family' => 'Averia Libre', 'variants' => array('n3', 'i3', 'n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'averia-libre'), 
    'averia-sans-libre' => array('family' => 'Averia Sans Libre', 'variants' => array('n3', 'i3', 'n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'averia-sans-libre'), 
    'averia-serif-libre' => array('family' => 'Averia Serif Libre', 'variants' => array('n3', 'i3', 'n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'averia-serif-libre'), 
    'bad-script' => array('family' => 'Bad Script', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'bad-script'), 
    'balthazar' => array('family' => 'Balthazar', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'balthazar'), 
    'bangers' => array('family' => 'Bangers', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'bangers'), 
    'basic' => array('family' => 'Basic', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'basic'), 
    'baumans' => array('family' => 'Baumans', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'baumans'), 
    'bebas-neue' => array('family' => 'Bebas Neue', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'bebas-neue'), 
    'belgrano' => array('family' => 'Belgrano', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'belgrano'), 
    'bentham' => array('family' => 'Bentham', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'bentham'), 
    'berkshire-swash' => array('family' => 'Berkshire Swash', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'berkshire-swash'), 
    'bigshot-one' => array('family' => 'Bigshot One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'bigshot-one'), 
    'bilbo' => array('family' => 'Bilbo', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'bilbo'), 
    'bilbo-swash-caps' => array('family' => 'Bilbo Swash Caps', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'bilbo-swash-caps'), 
    'bitter' => array('family' => 'Bitter', 'variants' => array('n4', 'i4', 'n7'), 'subsets' => array(''), 'slug' => 'bitter'), 
    'black-ops-one' => array('family' => 'Black Ops One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'black-ops-one'), 
    'bonbon' => array('family' => 'Bonbon', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'bonbon'), 
    'boogaloo' => array('family' => 'Boogaloo', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'boogaloo'), 
    'bowlby-one' => array('family' => 'Bowlby One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'bowlby-one'), 
    'bowlby-one-sc' => array('family' => 'Bowlby One SC', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'bowlby-one-sc'), 
    'brawler' => array('family' => 'Brawler', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'brawler'), 
    'bree-serif' => array('family' => 'Bree Serif', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'bree-serif'), 
    'brush-script-std' => array('family' => 'Brush Script Std', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'brush-script-std'), 
    'bubblegum-sans' => array('family' => 'Bubblegum Sans', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'bubblegum-sans'), 
    'bubbler-one' => array('family' => 'Bubbler One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'bubbler-one'), 
    'buda' => array('family' => 'Buda', 'variants' => array('n3'), 'subsets' => array(''), 'slug' => 'buda'), 
    'buenard' => array('family' => 'Buenard', 'variants' => array('n4', 'n7'), 'subsets' => array(''), 'slug' => 'buenard'), 
    'butcherman' => array('family' => 'Butcherman', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'butcherman'), 
    'butcherman-caps' => array('family' => 'Butcherman Caps', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'butcherman-caps'), 
    'butterfly-kids' => array('family' => 'Butterfly Kids', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'butterfly-kids'), 
    'cabin' => array('family' => 'Cabin', 'variants' => array('n4', 'i4', 'n5', 'i5', 'n6', 'i6', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'cabin'), 
    'cabin-condensed' => array('family' => 'Cabin Condensed', 'variants' => array('n4', 'n5', 'n6', 'n7'), 'subsets' => array(''), 'slug' => 'cabin-condensed'), 
    'cabin-sketch' => array('family' => 'Cabin Sketch', 'variants' => array('n4', 'n7'), 'subsets' => array(''), 'slug' => 'cabin-sketch'), 
    'caesar-dressing' => array('family' => 'Caesar Dressing', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'caesar-dressing'), 
    'cagliostro' => array('family' => 'Cagliostro', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'cagliostro'), 
    'calligraffitti' => array('family' => 'Calligraffitti', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'calligraffitti'), 
    'cambo' => array('family' => 'Cambo', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'cambo'), 
    'cantarell' => array('family' => 'Cantarell', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'cantarell'), 
    'cantata-one' => array('family' => 'Cantata One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'cantata-one'), 
    'cardo' => array('family' => 'Cardo', 'variants' => array('n4', 'i4', 'n7'), 'subsets' => array(''), 'slug' => 'cardo'), 
    'carme' => array('family' => 'Carme', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'carme'), 
    'carter-one' => array('family' => 'Carter One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'carter-one'), 
    'caudex' => array('family' => 'Caudex', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'caudex'), 
    'cedarville-cursive' => array('family' => 'Cedarville Cursive', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'cedarville-cursive'), 
    'ceviche-one' => array('family' => 'Ceviche One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'ceviche-one'), 
    'changa-one' => array('family' => 'Changa One', 'variants' => array('n4', 'i4'), 'subsets' => array(''), 'slug' => 'changa-one'), 
    'chango' => array('family' => 'Chango', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'chango'), 
    'chelsea-market' => array('family' => 'Chelsea Market', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'chelsea-market'), 
    'cherry-cream-soda' => array('family' => 'Cherry Cream Soda', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'cherry-cream-soda'), 
    'chewy' => array('family' => 'Chewy', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'chewy'), 
    'chicle' => array('family' => 'Chicle', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'chicle'), 
    'chivo' => array('family' => 'Chivo', 'variants' => array('n4', 'i4', 'n9', 'i9'), 'subsets' => array(''), 'slug' => 'chivo'), 
    'chunk' => array('family' => 'Chunk', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'chunk'), 
    'clara' => array('family' => 'Clara', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'clara'), 
    'coda' => array('family' => 'Coda', 'variants' => array('n4', 'n8'), 'subsets' => array(''), 'slug' => 'coda'), 
    'coda-caption' => array('family' => 'Coda Caption', 'variants' => array('n8'), 'subsets' => array(''), 'slug' => 'coda-caption'), 
    'codystar' => array('family' => 'Codystar', 'variants' => array('n3', 'n4'), 'subsets' => array(''), 'slug' => 'codystar'), 
    'comfortaa' => array('family' => 'Comfortaa', 'variants' => array('n3', 'n4', 'n7'), 'subsets' => array(''), 'slug' => 'comfortaa'), 
    'coming-soon' => array('family' => 'Coming Soon', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'coming-soon'), 
    'concert-one' => array('family' => 'Concert One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'concert-one'), 
    'condiment' => array('family' => 'Condiment', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'condiment'), 
    'contrail-one' => array('family' => 'Contrail One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'contrail-one'), 
    'convergence' => array('family' => 'Convergence', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'convergence'), 
    'cookie' => array('family' => 'Cookie', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'cookie'), 
    'cooper-black-std' => array('family' => 'Cooper Black Std', 'variants' => array('n4', 'i4'), 'subsets' => array(''), 'slug' => 'cooper-black-std'), 
    'copse' => array('family' => 'Copse', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'copse'), 
    'corben' => array('family' => 'Corben', 'variants' => array('n4', 'n7'), 'subsets' => array(''), 'slug' => 'corben'), 
    'cousine' => array('family' => 'Cousine', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'cousine'), 
    'coustard' => array('family' => 'Coustard', 'variants' => array('n4', 'n9'), 'subsets' => array(''), 'slug' => 'coustard'), 
    'covered-by-your-grace' => array('family' => 'Covered By Your Grace', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'covered-by-your-grace'), 
    'crafty-girls' => array('family' => 'Crafty Girls', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'crafty-girls'), 
    'creepster' => array('family' => 'Creepster', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'creepster'), 
    'creepster-caps' => array('family' => 'Creepster Caps', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'creepster-caps'), 
    'crete-round' => array('family' => 'Crete Round', 'variants' => array('n4', 'i4'), 'subsets' => array(''), 'slug' => 'crete-round'), 
    'crimson-text' => array('family' => 'Crimson Text', 'variants' => array('n4', 'i4', 'n6', 'i6', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'crimson-text'), 
    'crushed' => array('family' => 'Crushed', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'crushed'), 
    'cuprum' => array('family' => 'Cuprum', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'cuprum'), 
    'cutive' => array('family' => 'Cutive', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'cutive'), 
    'damion' => array('family' => 'Damion', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'damion'), 
    'dancing-script' => array('family' => 'Dancing Script', 'variants' => array('n4', 'n7'), 'subsets' => array(''), 'slug' => 'dancing-script'), 
    'dawning-of-a-new-day' => array('family' => 'Dawning of a New Day', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'dawning-of-a-new-day'), 
    'days-one' => array('family' => 'Days One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'days-one'), 
    'de-walpergens-pica' => array('family' => 'De Walpergen\'s Pica', 'variants' => array('n4', 'i4'), 'subsets' => array(''), 'slug' => 'de-walpergens-pica'), 
    'de-walpergens-pica-small-caps' => array('family' => 'De Walpergen\'s Pica Small Caps', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'de-walpergens-pica-small-caps'), 
    'delius' => array('family' => 'Delius', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'delius'), 
    'delius-swash-caps' => array('family' => 'Delius Swash Caps', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'delius-swash-caps'), 
    'delius-unicase' => array('family' => 'Delius Unicase', 'variants' => array('n4', 'n7'), 'subsets' => array(''), 'slug' => 'delius-unicase'), 
    'devonshire' => array('family' => 'Devonshire', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'devonshire'), 
    'dhyana' => array('family' => 'Dhyana', 'variants' => array('n4', 'n7'), 'subsets' => array(''), 'slug' => 'dhyana'), 
    'didact-gothic' => array('family' => 'Didact Gothic', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'didact-gothic'), 
    'diplomata' => array('family' => 'Diplomata', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'diplomata'), 
    'diplomata-sc' => array('family' => 'Diplomata SC', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'diplomata-sc'), 
    'doppio-one' => array('family' => 'Doppio One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'doppio-one'), 
    'dorsa' => array('family' => 'Dorsa', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'dorsa'), 
    'dosis' => array('family' => 'Dosis', 'variants' => array('n2', 'n3', 'n4', 'n5', 'n6', 'n7', 'n8'), 'subsets' => array(''), 'slug' => 'dosis'), 
    'double-pica' => array('family' => 'Double Pica', 'variants' => array('n4', 'i4'), 'subsets' => array(''), 'slug' => 'double-pica'), 
    'double-pica-small-caps' => array('family' => 'Double Pica Small Caps', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'double-pica-small-caps'), 
    'dr-sugiyama' => array('family' => 'Dr Sugiyama', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'dr-sugiyama'), 
    'droid-sans' => array('family' => 'Droid Sans', 'variants' => array('n4', 'n7'), 'subsets' => array(''), 'slug' => 'droid-sans'), 
    'droid-sans-mono' => array('family' => 'Droid Sans Mono', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'droid-sans-mono'), 
    'droid-serif' => array('family' => 'Droid Serif', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'droid-serif'), 
    'duru-sans' => array('family' => 'Duru Sans', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'duru-sans'), 
    'dynalight' => array('family' => 'Dynalight', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'dynalight'), 
    'eb-garamond' => array('family' => 'EB Garamond', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'eb-garamond'), 
    'eater' => array('family' => 'Eater', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'eater'), 
    'eater-caps' => array('family' => 'Eater Caps', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'eater-caps'), 
    'economica' => array('family' => 'Economica', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'economica'), 
    'electrolize' => array('family' => 'Electrolize', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'electrolize'), 
    'emblema-one' => array('family' => 'Emblema One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'emblema-one'), 
    'emilys-candy' => array('family' => 'Emilys Candy', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'emilys-candy'), 
    'engagement' => array('family' => 'Engagement', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'engagement'), 
    'english' => array('family' => 'English', 'variants' => array('n4', 'i4'), 'subsets' => array(''), 'slug' => 'english'), 
    'english-small-caps' => array('family' => 'English Small Caps', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'english-small-caps'), 
    'enriqueta' => array('family' => 'Enriqueta', 'variants' => array('n4', 'n7'), 'subsets' => array(''), 'slug' => 'enriqueta'), 
    'erica-one' => array('family' => 'Erica One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'erica-one'), 
    'esteban' => array('family' => 'Esteban', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'esteban'), 
    'euphoria-script' => array('family' => 'Euphoria Script', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'euphoria-script'), 
    'ewert' => array('family' => 'Ewert', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'ewert'), 
    'exo' => array('family' => 'Exo', 'variants' => array('n1', 'i1', 'n2', 'i2', 'n3', 'i3', 'n4', 'i4', 'n5', 'i5', 'n6', 'i6', 'n7', 'i7', 'n8', 'i8', 'n9', 'i9'), 'subsets' => array(''), 'slug' => 'exo'), 
    'expletus-sans' => array('family' => 'Expletus Sans', 'variants' => array('n4', 'i4', 'n5', 'i5', 'n6', 'i6', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'expletus-sans'), 
    'fanwood-text' => array('family' => 'Fanwood Text', 'variants' => array('n4', 'i4'), 'subsets' => array(''), 'slug' => 'fanwood-text'), 
    'fascinate' => array('family' => 'Fascinate', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'fascinate'), 
    'fascinate-inline' => array('family' => 'Fascinate Inline', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'fascinate-inline'), 
    'federant' => array('family' => 'Federant', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'federant'), 
    'federo' => array('family' => 'Federo', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'federo'), 
    'felipa' => array('family' => 'Felipa', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'felipa'), 
    'flamenco' => array('family' => 'Flamenco', 'variants' => array('n3', 'n4'), 'subsets' => array(''), 'slug' => 'flamenco'), 
    'flavors' => array('family' => 'Flavors', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'flavors'), 
    'fondamento' => array('family' => 'Fondamento', 'variants' => array('n4', 'i4'), 'subsets' => array(''), 'slug' => 'fondamento'), 
    'fontdiner-swanky' => array('family' => 'Fontdiner Swanky', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'fontdiner-swanky'), 
    'forum' => array('family' => 'Forum', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'forum'), 
    'fredericka-the-great' => array('family' => 'Fredericka the Great', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'fredericka-the-great'), 
    'fredoka-one' => array('family' => 'Fredoka One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'fredoka-one'), 
    'french-canon' => array('family' => 'French Canon', 'variants' => array('n4', 'i4'), 'subsets' => array(''), 'slug' => 'french-canon'), 
    'french-canon-small-caps' => array('family' => 'French Canon Small Caps', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'french-canon-small-caps'), 
    'fresca' => array('family' => 'Fresca', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'fresca'), 
    'frijole' => array('family' => 'Frijole', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'frijole'), 
    'fugaz-one' => array('family' => 'Fugaz One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'fugaz-one'), 
    'fusaka-std' => array('family' => 'Fusaka Std', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'fusaka-std'), 
    'gfs-didot' => array('family' => 'GFS Didot', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'gfs-didot'), 
    'gfs-neohellenic' => array('family' => 'GFS Neohellenic', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'gfs-neohellenic'), 
    'galdeano' => array('family' => 'Galdeano', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'galdeano'), 
    'gentium-basic' => array('family' => 'Gentium Basic', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'gentium-basic'), 
    'gentium-book-basic' => array('family' => 'Gentium Book Basic', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'gentium-book-basic'), 
    'geo' => array('family' => 'Geo', 'variants' => array('n4', 'i4'), 'subsets' => array(''), 'slug' => 'geo'), 
    'geostar' => array('family' => 'Geostar', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'geostar'), 
    'geostar-fill' => array('family' => 'Geostar Fill', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'geostar-fill'), 
    'germania-one' => array('family' => 'Germania One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'germania-one'), 
    'giddyup-std' => array('family' => 'Giddyup Std', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'giddyup-std'), 
    'give-you-glory' => array('family' => 'Give You Glory', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'give-you-glory'), 
    'glass-antiqua' => array('family' => 'Glass Antiqua', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'glass-antiqua'), 
    'glegoo' => array('family' => 'Glegoo', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'glegoo'), 
    'gloria-hallelujah' => array('family' => 'Gloria Hallelujah', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'gloria-hallelujah'), 
    'goblin-one' => array('family' => 'Goblin One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'goblin-one'), 
    'gochi-hand' => array('family' => 'Gochi Hand', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'gochi-hand'), 
    'gorditas' => array('family' => 'Gorditas', 'variants' => array('n4', 'n7'), 'subsets' => array(''), 'slug' => 'gorditas'), 
    'goudy-bookletter-1911' => array('family' => 'Goudy Bookletter 1911', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'goudy-bookletter-1911'), 
    'graduate' => array('family' => 'Graduate', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'graduate'), 
    'gravitas-one' => array('family' => 'Gravitas One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'gravitas-one'), 
    'great-primer' => array('family' => 'Great Primer', 'variants' => array('n4', 'i4'), 'subsets' => array(''), 'slug' => 'great-primer'), 
    'great-primer-small-caps' => array('family' => 'Great Primer Small Caps', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'great-primer-small-caps'), 
    'gruppo' => array('family' => 'Gruppo', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'gruppo'), 
    'gudea' => array('family' => 'Gudea', 'variants' => array('n4', 'i4', 'n7'), 'subsets' => array(''), 'slug' => 'gudea'), 
    'habibi' => array('family' => 'Habibi', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'habibi'), 
    'hammersmith-one' => array('family' => 'Hammersmith One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'hammersmith-one'), 
    'handlee' => array('family' => 'Handlee', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'handlee'), 
    'happy-monkey' => array('family' => 'Happy Monkey', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'happy-monkey'), 
    'henny-penny' => array('family' => 'Henny Penny', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'henny-penny'), 
    'herr-von-muellerhoff' => array('family' => 'Herr Von Muellerhoff', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'herr-von-muellerhoff'), 
    'hobo-std' => array('family' => 'Hobo Std', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'hobo-std'), 
    'holtwood-one-sc' => array('family' => 'Holtwood One SC', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'holtwood-one-sc'), 
    'homemade-apple' => array('family' => 'Homemade Apple', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'homemade-apple'), 
    'homenaje' => array('family' => 'Homenaje', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'homenaje'), 
    'iceberg' => array('family' => 'Iceberg', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'iceberg'), 
    'iceland' => array('family' => 'Iceland', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'iceland'), 
    'immi-five-of-five' => array('family' => 'Immi Five Of Five', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'immi-five-of-five'), 
    'imprima' => array('family' => 'Imprima', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'imprima'), 
    'inconsolata' => array('family' => 'Inconsolata', 'variants' => array('n5', 'n7'), 'subsets' => array(''), 'slug' => 'inconsolata'), 
    'inder' => array('family' => 'Inder', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'inder'), 
    'indie-flower' => array('family' => 'Indie Flower', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'indie-flower'), 
    'inika' => array('family' => 'Inika', 'variants' => array('n4', 'n7'), 'subsets' => array(''), 'slug' => 'inika'), 
    'irish-grover' => array('family' => 'Irish Grover', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'irish-grover'), 
    'irish-growler' => array('family' => 'Irish Growler', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'irish-growler'), 
    'istok-web' => array('family' => 'Istok Web', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'istok-web'), 
    'italiana' => array('family' => 'Italiana', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'italiana'), 
    'italianno' => array('family' => 'Italianno', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'italianno'), 
    'jim-nightshade' => array('family' => 'Jim Nightshade', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'jim-nightshade'), 
    'jockey-one' => array('family' => 'Jockey One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'jockey-one'), 
    'jolly-lodger' => array('family' => 'Jolly Lodger', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'jolly-lodger'), 
    'josefin-sans' => array('family' => 'Josefin Sans', 'variants' => array('n1', 'i1', 'n3', 'i3', 'n4', 'i4', 'n6', 'i6', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'josefin-sans'), 
    'josefin-slab' => array('family' => 'Josefin Slab', 'variants' => array('n1', 'i1', 'n3', 'i3', 'n4', 'i4', 'n6', 'i6', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'josefin-slab'), 
    'judson' => array('family' => 'Judson', 'variants' => array('n4', 'i4', 'n7'), 'subsets' => array(''), 'slug' => 'judson'), 
    'julee' => array('family' => 'Julee', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'julee'), 
    'junge' => array('family' => 'Junge', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'junge'), 
    'jura' => array('family' => 'Jura', 'variants' => array('n3', 'n4', 'n5', 'n6'), 'subsets' => array(''), 'slug' => 'jura'), 
    'just-another-hand' => array('family' => 'Just Another Hand', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'just-another-hand'), 
    'just-me-again-down-here' => array('family' => 'Just Me Again Down Here', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'just-me-again-down-here'), 
    'kaffeesatz' => array('family' => 'Kaffeesatz', 'variants' => array('n1', 'n3', 'n4', 'n7'), 'subsets' => array(''), 'slug' => 'kaffeesatz'), 
    'kameron' => array('family' => 'Kameron', 'variants' => array('n4', 'n7'), 'subsets' => array(''), 'slug' => 'kameron'), 
    'karla' => array('family' => 'Karla', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'karla'), 
    'kaushan-script' => array('family' => 'Kaushan Script', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'kaushan-script'), 
    'kelly-slab' => array('family' => 'Kelly Slab', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'kelly-slab'), 
    'kenia' => array('family' => 'Kenia', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'kenia'), 
    'knewave' => array('family' => 'Knewave', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'knewave'), 
    'kotta-one' => array('family' => 'Kotta One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'kotta-one'), 
    'kranky' => array('family' => 'Kranky', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'kranky'), 
    'kreon' => array('family' => 'Kreon', 'variants' => array('n3', 'n4', 'n7'), 'subsets' => array(''), 'slug' => 'kreon'), 
    'kristi' => array('family' => 'Kristi', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'kristi'), 
    'krona-one' => array('family' => 'Krona One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'krona-one'), 
    'la-belle-aurore' => array('family' => 'La Belle Aurore', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'la-belle-aurore'), 
    'lancelot' => array('family' => 'Lancelot', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'lancelot'), 
    'lateef' => array('family' => 'Lateef', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'lateef'), 
    'lato' => array('family' => 'Lato', 'variants' => array('n1', 'i1', 'n3', 'i3', 'n4', 'i4', 'n7', 'i7', 'n9', 'i9'), 'subsets' => array(''), 'slug' => 'lato'), 
    'league-gothic' => array('family' => 'League Gothic', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'league-gothic'), 
    'leckerli-one' => array('family' => 'Leckerli One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'leckerli-one'), 
    'ledger' => array('family' => 'Ledger', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'ledger'), 
    'lekton' => array('family' => 'Lekton', 'variants' => array('n4', 'i4', 'n7'), 'subsets' => array(''), 'slug' => 'lekton'), 
    'lemon' => array('family' => 'Lemon', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'lemon'), 
    'lilita-one' => array('family' => 'Lilita One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'lilita-one'), 
    'linden-hill' => array('family' => 'Linden Hill', 'variants' => array('n4', 'i4'), 'subsets' => array(''), 'slug' => 'linden-hill'), 
    'lobster' => array('family' => 'Lobster', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'lobster'), 
    'lobster-two' => array('family' => 'Lobster Two', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'lobster-two'), 
    'londrina-outline' => array('family' => 'Londrina Outline', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'londrina-outline'), 
    'londrina-shadow' => array('family' => 'Londrina Shadow', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'londrina-shadow'), 
    'londrina-sketch' => array('family' => 'Londrina Sketch', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'londrina-sketch'), 
    'londrina-solid' => array('family' => 'Londrina Solid', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'londrina-solid'), 
    'lora' => array('family' => 'Lora', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'lora'), 
    'love-ya-like-a-sister' => array('family' => 'Love Ya Like A Sister', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'love-ya-like-a-sister'), 
    'loved-by-the-king' => array('family' => 'Loved by the King', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'loved-by-the-king'), 
    'luckiest-guy' => array('family' => 'Luckiest Guy', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'luckiest-guy'), 
    'lusitana' => array('family' => 'Lusitana', 'variants' => array('n4', 'n7'), 'subsets' => array(''), 'slug' => 'lusitana'), 
    'lustria' => array('family' => 'Lustria', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'lustria'), 
    'm-1c' => array('family' => 'M+ 1c', 'variants' => array('n2', 'n3', 'n4', 'n5', 'n7', 'n8', 'n9'), 'subsets' => array(''), 'slug' => 'm-1c'), 
    'm-1m' => array('family' => 'M+ 1m', 'variants' => array('n1', 'n2', 'n4', 'n5', 'n7'), 'subsets' => array(''), 'slug' => 'm-1m'), 
    'macondo' => array('family' => 'Macondo', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'macondo'), 
    'macondo-swash-caps' => array('family' => 'Macondo Swash Caps', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'macondo-swash-caps'), 
    'maiden-orange' => array('family' => 'Maiden Orange', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'maiden-orange'), 
    'mako' => array('family' => 'Mako', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'mako'), 
    'marck-script' => array('family' => 'Marck Script', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'marck-script'), 
    'marko-one' => array('family' => 'Marko One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'marko-one'), 
    'marmelad' => array('family' => 'Marmelad', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'marmelad'), 
    'marvel' => array('family' => 'Marvel', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'marvel'), 
    'mate' => array('family' => 'Mate', 'variants' => array('n4', 'i4'), 'subsets' => array(''), 'slug' => 'mate'), 
    'mate-sc' => array('family' => 'Mate SC', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'mate-sc'), 
    'maven-pro' => array('family' => 'Maven Pro', 'variants' => array('n4', 'n5', 'n7', 'n9'), 'subsets' => array(''), 'slug' => 'maven-pro'), 
    'meddon' => array('family' => 'Meddon', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'meddon'), 
    'medievalsharp' => array('family' => 'MedievalSharp', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'medievalsharp'), 
    'medula-one' => array('family' => 'Medula One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'medula-one'), 
    'megrim' => array('family' => 'Megrim', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'megrim'), 
    'merienda-one' => array('family' => 'Merienda One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'merienda-one'), 
    'merriweather' => array('family' => 'Merriweather', 'variants' => array('n3', 'n4', 'n7', 'n9'), 'subsets' => array(''), 'slug' => 'merriweather'), 
    'metamorphous' => array('family' => 'Metamorphous', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'metamorphous'), 
    'miama' => array('family' => 'Miama', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'miama'), 
    'miltonian' => array('family' => 'Miltonian', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'miltonian'), 
    'miltonian-tattoo' => array('family' => 'Miltonian Tattoo', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'miltonian-tattoo'), 
    'miniver' => array('family' => 'Miniver', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'miniver'), 
    'miss-fajardose' => array('family' => 'Miss Fajardose', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'miss-fajardose'), 
    'miss-saint-delafield' => array('family' => 'Miss Saint Delafield', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'miss-saint-delafield'), 
    'modern-antiqua' => array('family' => 'Modern Antiqua', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'modern-antiqua'), 
    'molengo' => array('family' => 'Molengo', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'molengo'), 
    'monofett' => array('family' => 'Monofett', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'monofett'), 
    'monoton' => array('family' => 'Monoton', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'monoton'), 
    'monsieur-la-doulaise' => array('family' => 'Monsieur La Doulaise', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'monsieur-la-doulaise'), 
    'montaga' => array('family' => 'Montaga', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'montaga'), 
    'montez' => array('family' => 'Montez', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'montez'), 
    'montserrat' => array('family' => 'Montserrat', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'montserrat'), 
    'mountains-of-christmas' => array('family' => 'Mountains of Christmas', 'variants' => array('n4', 'n7'), 'subsets' => array(''), 'slug' => 'mountains-of-christmas'), 
    'mr-bedfort' => array('family' => 'Mr Bedfort', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'mr-bedfort'), 
    'mr-dafoe' => array('family' => 'Mr Dafoe', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'mr-dafoe'), 
    'mr-de-haviland' => array('family' => 'Mr De Haviland', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'mr-de-haviland'), 
    'mrs-saint-delafield' => array('family' => 'Mrs Saint Delafield', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'mrs-saint-delafield'), 
    'mrs-sheppards' => array('family' => 'Mrs Sheppards', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'mrs-sheppards'), 
    'muli' => array('family' => 'Muli', 'variants' => array('n3', 'i3', 'n4', 'i4'), 'subsets' => array(''), 'slug' => 'muli'), 
    'mystery-quest' => array('family' => 'Mystery Quest', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'mystery-quest'), 
    'neuton' => array('family' => 'Neuton', 'variants' => array('n2', 'n3', 'n4', 'i4', 'n7', 'n8'), 'subsets' => array(''), 'slug' => 'neuton'), 
    'neuton-cursive' => array('family' => 'Neuton Cursive', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'neuton-cursive'), 
    'niconne' => array('family' => 'Niconne', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'niconne'), 
    'nixie-one' => array('family' => 'Nixie One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'nixie-one'), 
    'nobile' => array('family' => 'Nobile', 'variants' => array('n4', 'i4', 'n5', 'i5', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'nobile'), 
    'norican' => array('family' => 'Norican', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'norican'), 
    'nosifer' => array('family' => 'Nosifer', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'nosifer'), 
    'nothing-you-could-do' => array('family' => 'Nothing You Could Do', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'nothing-you-could-do'), 
    'noticia-text' => array('family' => 'Noticia Text', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'noticia-text'), 
    'nova-cut' => array('family' => 'Nova Cut', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'nova-cut'), 
    'nova-flat' => array('family' => 'Nova Flat', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'nova-flat'), 
    'nova-mono' => array('family' => 'Nova Mono', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'nova-mono'), 
    'nova-oval' => array('family' => 'Nova Oval', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'nova-oval'), 
    'nova-round' => array('family' => 'Nova Round', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'nova-round'), 
    'nova-script' => array('family' => 'Nova Script', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'nova-script'), 
    'nova-slim' => array('family' => 'Nova Slim', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'nova-slim'), 
    'nova-square' => array('family' => 'Nova Square', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'nova-square'), 
    'numans' => array('family' => 'Numans', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'numans'), 
    'nunito' => array('family' => 'Nunito', 'variants' => array('n3', 'n4', 'n7'), 'subsets' => array(''), 'slug' => 'nunito'), 
    'old-standard' => array('family' => 'Old Standard', 'variants' => array('n4', 'i4', 'n7'), 'subsets' => array(''), 'slug' => 'old-standard'), 
    'oldenburg' => array('family' => 'Oldenburg', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'oldenburg'), 
    'open-sans' => array('family' => 'Open Sans', 'variants' => array('n3', 'i3', 'n4', 'i4', 'n6', 'i6', 'n7', 'i7', 'n8', 'i8'), 'subsets' => array(''), 'slug' => 'open-sans'), 
    'open-sans-condensed' => array('family' => 'Open Sans Condensed', 'variants' => array('n3', 'i3', 'n7'), 'subsets' => array(''), 'slug' => 'open-sans-condensed'), 
    'orbitron' => array('family' => 'Orbitron', 'variants' => array('n3', 'n5', 'n7', 'n9'), 'subsets' => array(''), 'slug' => 'orbitron'), 
    'original-surfer' => array('family' => 'Original Surfer', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'original-surfer'), 
    'over-the-rainbow' => array('family' => 'Over the Rainbow', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'over-the-rainbow'), 
    'overlock' => array('family' => 'Overlock', 'variants' => array('n4', 'i4', 'n7', 'i7', 'n9', 'i9'), 'subsets' => array(''), 'slug' => 'overlock'), 
    'overlock-sc' => array('family' => 'Overlock SC', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'overlock-sc'), 
    'ovo' => array('family' => 'Ovo', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'ovo'), 
    'pt-mono' => array('family' => 'PT Mono', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'pt-mono'), 
    'pt-sans' => array('family' => 'PT Sans', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'pt-sans'), 
    'pt-sans-caption' => array('family' => 'PT Sans Caption', 'variants' => array('n4', 'n7'), 'subsets' => array(''), 'slug' => 'pt-sans-caption'), 
    'pt-sans-narrow' => array('family' => 'PT Sans Narrow', 'variants' => array('n4', 'n7'), 'subsets' => array(''), 'slug' => 'pt-sans-narrow'), 
    'pt-serif' => array('family' => 'PT Serif', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'pt-serif'), 
    'pt-serif-caption' => array('family' => 'PT Serif Caption', 'variants' => array('n4', 'i4'), 'subsets' => array(''), 'slug' => 'pt-serif-caption'), 
    'pacifico' => array('family' => 'Pacifico', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'pacifico'), 
    'parisienne' => array('family' => 'Parisienne', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'parisienne'), 
    'passero-one' => array('family' => 'Passero One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'passero-one'), 
    'passion-one' => array('family' => 'Passion One', 'variants' => array('n4', 'n7', 'n9'), 'subsets' => array(''), 'slug' => 'passion-one'), 
    'patrick-hand' => array('family' => 'Patrick Hand', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'patrick-hand'), 
    'patua-one' => array('family' => 'Patua One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'patua-one'), 
    'paytone-one' => array('family' => 'Paytone One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'paytone-one'), 
    'permanent-marker' => array('family' => 'Permanent Marker', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'permanent-marker'), 
    'petrona' => array('family' => 'Petrona', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'petrona'), 
    'philosopher' => array('family' => 'Philosopher', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'philosopher'), 
    'piedra' => array('family' => 'Piedra', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'piedra'), 
    'pinyon-script' => array('family' => 'Pinyon Script', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'pinyon-script'), 
    'plaster' => array('family' => 'Plaster', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'plaster'), 
    'play' => array('family' => 'Play', 'variants' => array('n4', 'n7'), 'subsets' => array(''), 'slug' => 'play'), 
    'playball' => array('family' => 'Playball', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'playball'), 
    'playfair-display' => array('family' => 'Playfair Display', 'variants' => array('n4', 'i4'), 'subsets' => array(''), 'slug' => 'playfair-display'), 
    'podkova' => array('family' => 'Podkova', 'variants' => array('n4', 'n7'), 'subsets' => array(''), 'slug' => 'podkova'), 
    'poiret-one' => array('family' => 'Poiret One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'poiret-one'), 
    'poller-one' => array('family' => 'Poller One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'poller-one'), 
    'poly' => array('family' => 'Poly', 'variants' => array('n4', 'i4'), 'subsets' => array(''), 'slug' => 'poly'), 
    'pompiere' => array('family' => 'Pompiere', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'pompiere'), 
    'pontano-sans' => array('family' => 'Pontano Sans', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'pontano-sans'), 
    'port-lligat-sans' => array('family' => 'Port Lligat Sans', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'port-lligat-sans'), 
    'port-lligat-slab' => array('family' => 'Port Lligat Slab', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'port-lligat-slab'), 
    'prata' => array('family' => 'Prata', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'prata'), 
    'princess-sofia' => array('family' => 'Princess Sofia', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'princess-sofia'), 
    'prosto-one' => array('family' => 'Prosto One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'prosto-one'), 
    'puritan' => array('family' => 'Puritan', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'puritan'), 
    'quantico' => array('family' => 'Quantico', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'quantico'), 
    'quattrocento' => array('family' => 'Quattrocento', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'quattrocento'), 
    'quattrocento-sans' => array('family' => 'Quattrocento Sans', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'quattrocento-sans'), 
    'questrial' => array('family' => 'Questrial', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'questrial'), 
    'quicksand' => array('family' => 'Quicksand', 'variants' => array('n3', 'i3', 'n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'quicksand'), 
    'qwigley' => array('family' => 'Qwigley', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'qwigley'), 
    'radley' => array('family' => 'Radley', 'variants' => array('n4', 'i4'), 'subsets' => array(''), 'slug' => 'radley'), 
    'raleway' => array('family' => 'Raleway', 'variants' => array('n1'), 'subsets' => array(''), 'slug' => 'raleway'), 
    'rammetto-one' => array('family' => 'Rammetto One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'rammetto-one'), 
    'rancho' => array('family' => 'Rancho', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'rancho'), 
    'rationale' => array('family' => 'Rationale', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'rationale'), 
    'redressed' => array('family' => 'Redressed', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'redressed'), 
    'reenie-beanie' => array('family' => 'Reenie Beanie', 'variants' => array('n5'), 'subsets' => array(''), 'slug' => 'reenie-beanie'), 
    'revalia' => array('family' => 'Revalia', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'revalia'), 
    'ribeye' => array('family' => 'Ribeye', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'ribeye'), 
    'ribeye-marrow' => array('family' => 'Ribeye Marrow', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'ribeye-marrow'), 
    'righteous' => array('family' => 'Righteous', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'righteous'), 
    'rochester' => array('family' => 'Rochester', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'rochester'), 
    'rock-salt' => array('family' => 'Rock Salt', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'rock-salt'), 
    'ropa-sans' => array('family' => 'Ropa Sans', 'variants' => array('n4', 'i4'), 'subsets' => array(''), 'slug' => 'ropa-sans'), 
    'rosario' => array('family' => 'Rosario', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'rosario'), 
    'rouge-script' => array('family' => 'Rouge Script', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'rouge-script'), 
    'ruda' => array('family' => 'Ruda', 'variants' => array('n4', 'n7', 'n9'), 'subsets' => array(''), 'slug' => 'ruda'), 
    'ruge-boogie' => array('family' => 'Ruge Boogie', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'ruge-boogie'), 
    'ruluko' => array('family' => 'Ruluko', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'ruluko'), 
    'ruslan-display' => array('family' => 'Ruslan Display', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'ruslan-display'), 
    'ruthie' => array('family' => 'Ruthie', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'ruthie'), 
    'sail' => array('family' => 'Sail', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'sail'), 
    'salsa' => array('family' => 'Salsa', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'salsa'), 
    'sancreek' => array('family' => 'Sancreek', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'sancreek'), 
    'sansita-one' => array('family' => 'Sansita One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'sansita-one'), 
    'sanvito-pro-display' => array('family' => 'Sanvito Pro Display', 'variants' => array('n7'), 'subsets' => array(''), 'slug' => 'sanvito-pro-display'), 
    'sarina' => array('family' => 'Sarina', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'sarina'), 
    'satisfy' => array('family' => 'Satisfy', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'satisfy'), 
    'schoolbell' => array('family' => 'Schoolbell', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'schoolbell'), 
    'seaweed-script' => array('family' => 'Seaweed Script', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'seaweed-script'), 
    'sevillana' => array('family' => 'Sevillana', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'sevillana'), 
    'shadows-into-light' => array('family' => 'Shadows Into Light', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'shadows-into-light'), 
    'shadows-into-light-two' => array('family' => 'Shadows Into Light Two', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'shadows-into-light-two'), 
    'shanti' => array('family' => 'Shanti', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'shanti'), 
    'share-regular' => array('family' => 'Share Regular', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'share-regular'), 
    'shojumaru' => array('family' => 'Shojumaru', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'shojumaru'), 
    'short-stack' => array('family' => 'Short Stack', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'short-stack'), 
    'shuriken-std' => array('family' => 'Shuriken Std', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'shuriken-std'), 
    'sigmar-one' => array('family' => 'Sigmar One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'sigmar-one'), 
    'simonetta' => array('family' => 'Simonetta', 'variants' => array('n4', 'i4'), 'subsets' => array(''), 'slug' => 'simonetta'), 
    'sirin-stencil' => array('family' => 'Sirin Stencil', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'sirin-stencil'), 
    'six-caps' => array('family' => 'Six Caps', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'six-caps'), 
    'slackey' => array('family' => 'Slackey', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'slackey'), 
    'smokum' => array('family' => 'Smokum', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'smokum'), 
    'smythe' => array('family' => 'Smythe', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'smythe'), 
    'sniglet' => array('family' => 'Sniglet', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'sniglet'), 
    'snippet' => array('family' => 'Snippet', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'snippet'), 
    'sofia' => array('family' => 'Sofia', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'sofia'), 
    'sonsie-one' => array('family' => 'Sonsie One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'sonsie-one'), 
    'sorts-mill-goudy' => array('family' => 'Sorts Mill Goudy', 'variants' => array('n5', 'i5'), 'subsets' => array(''), 'slug' => 'sorts-mill-goudy'), 
    'source-code-pro' => array('family' => 'Source Code Pro', 'variants' => array('n2', 'n3', 'n4', 'n6', 'n7', 'n9'), 'subsets' => array(''), 'slug' => 'source-code-pro'), 
    'source-sans-pro' => array('family' => 'Source Sans Pro', 'variants' => array('n2', 'i2', 'n3', 'i3', 'n4', 'i4', 'n6', 'i6', 'n7', 'i7', 'n9', 'i9'), 'subsets' => array(''), 'slug' => 'source-sans-pro'), 
    'special-elite' => array('family' => 'Special Elite', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'special-elite'), 
    'spicy-rice' => array('family' => 'Spicy Rice', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'spicy-rice'), 
    'spinnaker' => array('family' => 'Spinnaker', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'spinnaker'), 
    'spirax' => array('family' => 'Spirax', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'spirax'), 
    'squada-one' => array('family' => 'Squada One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'squada-one'), 
    'stardos-stencil' => array('family' => 'Stardos Stencil', 'variants' => array('n4', 'n7'), 'subsets' => array(''), 'slug' => 'stardos-stencil'), 
    'stencil-std' => array('family' => 'Stencil Std', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'stencil-std'), 
    'stint-ultra-condensed' => array('family' => 'Stint Ultra Condensed', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'stint-ultra-condensed'), 
    'stint-ultra-expanded' => array('family' => 'Stint Ultra Expanded', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'stint-ultra-expanded'), 
    'stoke' => array('family' => 'Stoke', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'stoke'), 
    'strong' => array('family' => 'Strong', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'strong'), 
    'strumpf-std' => array('family' => 'Strumpf Std', 'variants' => array('n7'), 'subsets' => array(''), 'slug' => 'strumpf-std'), 
    'sue-ellen-francisco' => array('family' => 'Sue Ellen Francisco', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'sue-ellen-francisco'), 
    'sunshiney' => array('family' => 'Sunshiney', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'sunshiney'), 
    'supermercado-one' => array('family' => 'Supermercado One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'supermercado-one'), 
    'swanky-and-moo-moo' => array('family' => 'Swanky and Moo Moo', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'swanky-and-moo-moo'), 
    'syncopate' => array('family' => 'Syncopate', 'variants' => array('n4', 'n7'), 'subsets' => array(''), 'slug' => 'syncopate'), 
    'tangerine' => array('family' => 'Tangerine', 'variants' => array('n4', 'n7'), 'subsets' => array(''), 'slug' => 'tangerine'), 
    'telex' => array('family' => 'Telex', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'telex'), 
    'tenor-sans' => array('family' => 'Tenor Sans', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'tenor-sans'), 
    'the-girl-next-door' => array('family' => 'The Girl Next Door', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'the-girl-next-door'), 
    'tienne' => array('family' => 'Tienne', 'variants' => array('n4', 'n7', 'n9'), 'subsets' => array(''), 'slug' => 'tienne'), 
    'tinos' => array('family' => 'Tinos', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'tinos'), 
    'titan-one' => array('family' => 'Titan One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'titan-one'), 
    'trade-winds' => array('family' => 'Trade Winds', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'trade-winds'), 
    'trochut' => array('family' => 'Trochut', 'variants' => array('n4', 'i4', 'n7'), 'subsets' => array(''), 'slug' => 'trochut'), 
    'trykker' => array('family' => 'Trykker', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'trykker'), 
    'tulpen-one' => array('family' => 'Tulpen One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'tulpen-one'), 
    'ubuntu' => array('family' => 'Ubuntu', 'variants' => array('n3', 'i3', 'n4', 'i4', 'n5', 'i5', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'ubuntu'), 
    'ubuntu-condensed' => array('family' => 'Ubuntu Condensed', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'ubuntu-condensed'), 
    'ubuntu-mono' => array('family' => 'Ubuntu Mono', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'ubuntu-mono'), 
    'ultra' => array('family' => 'Ultra', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'ultra'), 
    'uncial-antiqua' => array('family' => 'Uncial Antiqua', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'uncial-antiqua'), 
    'unifrakturcook' => array('family' => 'UnifrakturCook', 'variants' => array('n7'), 'subsets' => array(''), 'slug' => 'unifrakturcook'), 
    'unifrakturmaguntia' => array('family' => 'UnifrakturMaguntia', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'unifrakturmaguntia'), 
    'unkempt' => array('family' => 'Unkempt', 'variants' => array('n4', 'n7'), 'subsets' => array(''), 'slug' => 'unkempt'), 
    'unlock' => array('family' => 'Unlock', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'unlock'), 
    'unna' => array('family' => 'Unna', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'unna'), 
    'vt323' => array('family' => 'VT323', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'vt323'), 
    'varela' => array('family' => 'Varela', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'varela'), 
    'varela-round' => array('family' => 'Varela Round', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'varela-round'), 
    'vast-shadow' => array('family' => 'Vast Shadow', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'vast-shadow'), 
    'vera-sans' => array('family' => 'Vera Sans', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'vera-sans'), 
    'vibur' => array('family' => 'Vibur', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'vibur'), 
    'vidaloka' => array('family' => 'Vidaloka', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'vidaloka'), 
    'viga' => array('family' => 'Viga', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'viga'), 
    'voces' => array('family' => 'Voces', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'voces'), 
    'volkhov' => array('family' => 'Volkhov', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'volkhov'), 
    'vollkorn' => array('family' => 'Vollkorn', 'variants' => array('n4', 'i4', 'n7', 'i7'), 'subsets' => array(''), 'slug' => 'vollkorn'), 
    'voltaire' => array('family' => 'Voltaire', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'voltaire'), 
    'waiting-for-the-sunrise' => array('family' => 'Waiting for the Sunrise', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'waiting-for-the-sunrise'), 
    'wallpoet' => array('family' => 'Wallpoet', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'wallpoet'), 
    'walter-turncoat' => array('family' => 'Walter Turncoat', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'walter-turncoat'), 
    'wellfleet' => array('family' => 'Wellfleet', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'wellfleet'), 
    'wire-one' => array('family' => 'Wire One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'wire-one'), 
    'yellowtail' => array('family' => 'Yellowtail', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'yellowtail'), 
    'yeseva-one' => array('family' => 'Yeseva One', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'yeseva-one'), 
    'yesteryear' => array('family' => 'Yesteryear', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'yesteryear'), 
    'zeyada' => array('family' => 'Zeyada', 'variants' => array('n4'), 'subsets' => array(''), 'slug' => 'zeyada')
);

?>